project:
  type: website

website:
  title: "Welcome to my Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Sindhujarao21
      - icon: twitter
        href: https://twitter.com/Sindhuj53282547
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

